name: Build & Publish Multi-Arch

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # 1) Linux: amd64 + arm64
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Linux images
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f Dockerfile.linux \
            -t azegler/hello-os:linux-latest \
            --push .

  # 2) Windows: amd64
    build-windows:
    runs-on: windows-latest
    needs: build-linux
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Windows image
        run: docker build -f Dockerfile.windows -t azegler/hello-os:windows-latest . && docker push azegler/hello-os:windows-latest


  # 3) Manifest latest
  create-manifest:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-windows
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push manifest
        run: |
          docker manifest create azegler/hello-os:latest \
            azegler/hello-os:linux-latest \
            azegler/hello-os:windows-latest
          docker manifest push azegler/hello-os:latest
