name: Build & Publish Multi-Arch

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, windows/amd64]
        dockerfile: [Dockerfile.linux, Dockerfile.linux, Dockerfile.windows]
        tag: [linux-latest, linux-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            -f ${{ matrix.dockerfile }} \
            -t azegler/hello-os:${{ matrix.tag }} \
            --push .

  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push manifest
        run: |
          docker manifest create azegler/hello-os:latest \
            azegler/hello-os:linux-latest \
            azegler/hello-os:windows-latest
          docker manifest push azegler/hello-os:latest
