# .github/workflows/build-and-push.yml
name: Build & Publish Multi-Arch

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # 1) Build & push Linux images (amd64 + arm64) on Ubuntu
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Linux amd64
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -f Dockerfile.linux \
            -t azegler/hello-os:linux-amd64 \
            --push .

      - name: Build & Push Linux arm64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -f Dockerfile.linux \
            -t azegler/hello-os:linux-arm64 \
            --push .

  # 2) Build & push Windows image (amd64) on Windows runner
  build-windows:
    runs-on: windows-latest
    needs: build-linux
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Windows image
        shell: bash
        run: |
          docker pull azegler/hello-os:windows-latest || true
          docker build --cache-from=azegler/hello-os:windows-latest \
            -f Dockerfile.windows \
            -t azegler/hello-os:windows-latest .
          docker push azegler/hello-os:windows-latest

    # 3) Create & Push manifest “latest”
  create-manifest:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-windows
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push combined manifest
        run: |
          docker buildx imagetools create \
          --tag azegler/hello-os:latest \
          azegler/hello-os:linux-latest \
          azegler/hello-os:windows-latest
